using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace employeeApi.Migrations
{
    /// <inheritdoc />
    public partial class init : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Employees",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    FullName = table.Column<string>(type: "varchar(256)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Employees", x => x.Id);
                });

            migrationBuilder.InsertData(
                table: "Employees",
                columns: new[] { "Id", "FullName" },
                values: new object[,]
                {
                    { 1, "MOHAMMAD FARID BIN MOHAMED YUNUS" },
                    { 2, "TEH BENG HOCK" },
                    { 3, "TEE YEW YAW" },
                    { 4, "AMEEN AMAENDRAN BIN ABDULLAH" },
                    { 5, "YONG HUAN LOON" },
                    { 6, "LIM WEI SEONG" },
                    { 7, "MEGAT ISHAK BIN MAAMUNOR RASHID" },
                    { 8, "HANIM BINTI MHD ASRAR" },
                    { 9, "MOHD FAIROS BIN SAID" },
                    { 10, "HUMAIRAH HUSNA BINTI MOHD ZAMRI" },
                    { 11, "LWEE WEN LING" },
                    { 12, "MOHAMMAD AMZAR BIN MOHAMAD KHIR" },
                    { 13, "MUHAMMAD ALIFF HAIQAL BIN AHMAD" },
                    { 14, "HARRIES BIN MOHAMAD" },
                    { 15, "KHAW HERN THANG " },
                    { 16, "FUN PIK LIN " },
                    { 17, "AMIRUL HAFIQ BIN ZULKEPLI" },
                    { 18, "LEOH CHIA CHEAK" },
                    { 19, "CHAN LAI FONG" },
                    { 20, "CHAN LOK FENG" },
                    { 21, "NUR HAZWANI BINTI KAMARUDDIN" },
                    { 22, "NOR FADILAH BINTI MOHD SHAMSUL MAARIF" },
                    { 23, "FATIN NADIRAH BINTI ZAHARI" },
                    { 24, "MOHAMMAD AZRI BIN MOHAMAD AZMI" },
                    { 25, "LIM SEN KEONG" },
                    { 26, "IJA MOHAN" },
                    { 27, "WOO ZI WEI" },
                    { 28, "VENOTHANEE A/P SUNDRA MOHAN" },
                    { 29, "TEE JOEY" },
                    { 30, "CHAN TIK CHOONG" },
                    { 31, "TEA BINXIONG" },
                    { 32, "LOW WAI KIT" },
                    { 33, "WAN JIA XING" },
                    { 34, "LOW KENG SIANG" },
                    { 35, "GLADYS CHENG PEI YIN" },
                    { 36, "NG YEW CHUN" },
                    { 37, "LEE LI LENG " },
                    { 38, "GUEK TAI SHAN" },
                    { 39, "AHMAD FAZLY BIN ABDULLAH" },
                    { 40, "CHUAH POW HONG" },
                    { 41, "GAN SIAW HUI     " },
                    { 42, "NG LAI HUI " },
                    { 43, "YANG FON MIN" },
                    { 44, "LEE KAH WAI" },
                    { 45, "LOW POH LIM" },
                    { 46, "CHYE ZEE CHING" },
                    { 47, "TEAW KHIN HONG" },
                    { 48, "GOH SWEET WAI" },
                    { 49, "MOHD FITRI BIN MOHD NASRUDIN" },
                    { 50, "NURHASNATUL AIDA BINTI SUHIZLIZANI IHSAN" },
                    { 51, "NORAISYAH BINTI ABDUL MAJID" },
                    { 52, "MOHAMAD SYUKRY BIN TAMSIR" },
                    { 53, "LEONG KAH MING" },
                    { 54, "EDWIN HO CHUN PHUN" },
                    { 55, "MOHD AMIRUL KHAIR BIN MOHD YUSUF" },
                    { 56, "SHERIL BINTI ABDUL AZIZ" },
                    { 57, "ALMANZO GARRY GAR" },
                    { 58, "ZAFFARUL IZNEE BIN MD NOH" },
                    { 59, "MUHAMAD SYAFIQ FARIS BIN NASRI" },
                    { 60, "TOO KIM YOONG" },
                    { 61, "TEH JU CHING" },
                    { 62, "TAN MEI HWA" },
                    { 63, "CHONG SITT YEAN" },
                    { 64, "HONG HUI MAY" },
                    { 65, "WONG SEE LIANG" },
                    { 66, "HO HWEE YEE" },
                    { 67, "LIM HOI CHIEN " },
                    { 68, "CHENG KEI MIE " },
                    { 69, "WAN SOOK FUN" },
                    { 70, "NG BEE BEE" },
                    { 71, "CHEN PEI SI" },
                    { 72, "NUR ANIS BINTI MOHAMMAD SAFARUDDIN" },
                    { 73, "ANIS DZULFAH BINTI DZULKIFLI" },
                    { 74, "WONG SIEW MOI" },
                    { 75, "MOHAMMAD SYAZWAN BIN SUPPIAN" },
                    { 76, "NAI SHI PEI" },
                    { 77, "AZREEN BINTI HAMDAN" },
                    { 78, "NURAIN BINTI ZULKIFLI" },
                    { 79, "NOR AFFRINA NABILA HUDA BINTI MAT ARIFF" },
                    { 80, "TAN BEE LEE " },
                    { 81, "SUBASHINEE A/P KUMARAN" },
                    { 82, "LEE YIN HAR " },
                    { 83, "LAI POU YEE" },
                    { 84, "ATHIRAH SALSABIILA BINTI MOHD ANAS" },
                    { 85, "SYAZA BINTI ZULKEPLI" },
                    { 86, "CHENG KHAI TENG" },
                    { 87, "TAN TIEN YEE" },
                    { 88, "CHOW SIEW LAI" },
                    { 89, "ZULAIKHA BINTI MOKHTAR" },
                    { 90, "LEE LAM BIN " },
                    { 91, "IDAYU BINTI MOKHTAR" },
                    { 92, "NURRAIN SYAHIRAH BINTI ISMAIL" },
                    { 93, "WAN NUR FATIN HANISAH BINTI MOHD FADZIL" },
                    { 94, "YONG YOKE CHOO" },
                    { 95, "NOR’AIN SHARMILA BINTI IBRAHIM" },
                    { 96, "AZMAN BIN NAIM" },
                    { 97, "\"SEAH CHING YIENG" },
                    { 98, "YEE PECK YAN " },
                    { 99, "SOFIA BINTI HISHAMUDDIN" },
                    { 100, "MOHAMAD DANIAL SOBA BIN MOHD SOBA" },
                    { 101, "YUHASHINEE A/P CHANDRASEGARAN" },
                    { 102, "MOHD TAUFIQ FIRDAUS BIN NOR AZLI" },
                    { 103, "MOHD NORFAHMY BIN MOHD ISMAIL" },
                    { 104, "NURAZNANIE BINTI MUHAMMAD" },
                    { 105, "ZUHAIRY BIN ZAIRUL NIZAM" },
                    { 106, "ONG POH CHOO " },
                    { 107, "MOHD NAZRI BIN HASHIM" },
                    { 108, "MOHAMAD SYAZWAN BIN ROSLAN" },
                    { 109, "NOR MOHD IKHWAN BIN PA'WAN" },
                    { 110, "NURAIZUNA SAFWA BINTI JAIS" },
                    { 111, "HIDAYATUL AKMAR BINTI MUHAMAD" },
                    { 112, "NIK HAFIZAH BINTI NIK MAT" },
                    { 113, "CHE MUNIRAH BINTI CHE MURAD" },
                    { 114, "NOR AZIZAH BINTI LUDDIN" },
                    { 115, "HAYATHI BT MOKHTAR" },
                    { 116, "ALVIN LOOK WAI HONG" },
                    { 117, "NUR WAHIDAH BINTI SHAMIN AHMAD" },
                    { 118, "NOOR ANINA BAIZURA BINTI ABDUL GHANI" },
                    { 119, "CHONG QIN WEI" },
                    { 120, "NURUL WASILAH BINTI MOHD MOKHTAR" },
                    { 121, "FATIN NABIHAH BINTI MD SAIRY" },
                    { 122, "WONG YE SIN" },
                    { 123, "SURIMA BINTI AHMAD ZAIDI        " },
                    { 124, "NOR BAYZURA BT MOHD SHAMSUL MAARIF" },
                    { 125, "ANZEE BINTI MASINGKAN" },
                    { 126, "MOHAMMAD HAFIZ BIN RUSDAN" },
                    { 127, "RUHIL AZIANI BINTI AZIZ" },
                    { 128, "HEMAVATHY A/P RAMACHANDRAN" },
                    { 129, "KHAIRUL FAHMY BIN RAZALI" },
                    { 130, "LAILA BINTI ZANUDIN" },
                    { 131, "NURUL IDAYAH BINTI DIL" },
                    { 132, "GEETA A/P RAJA GHAPAL" },
                    { 133, "NURUL NADIAH BINTI MOHAMAD FAIZAL" },
                    { 134, "NURUL FARZANA BINTI THULKARUNAI" },
                    { 135, "CHAN CHIA YI" },
                    { 136, "NUR FARAHANA BINTI AHMAD" },
                    { 137, "NUR HAZWANY BINTI RUZLI" },
                    { 138, "NOORHAYATI BINTI MOHD SALLEH" },
                    { 139, "NURUL AFIQAH BINTI YAHYA" },
                    { 140, "NURSYAFIQAH ALIAH BINTI MAT RAPI" },
                    { 141, "AINOR AININA BINTI JAIDI" },
                    { 142, "NORHAYATI BINTI JAMALUDIN" },
                    { 143, "SITI ROHAYU BINTI AHMAD" },
                    { 144, "NUR AQILAH BINTI MUDZAMIL" },
                    { 145, "SUKRI NAZRI BIN MOHD SUKIR" },
                    { 146, "ZAILINA BINTI JAINUDEEN" },
                    { 147, "NURLIZAH BINTI BAHTIAR" },
                    { 148, "NUR LIYANA BINTI JAAFAR" },
                    { 149, "PUTRI NUR FATIMATULZAHARA BINTI SAFRI" },
                    { 150, "NUR AMELIA BINTI AHMAD" },
                    { 151, "AWGKU A'AFDALLUL AMAL ASYRAF" },
                    { 152, "MEGAWATI BINTI ABDUL RAHMAN" },
                    { 153, "SU KON KEN" },
                    { 154, "HARITS MOHAMMAD BIN MAZLAN" },
                    { 155, "NURUL KATIKA BINTI RASID" },
                    { 156, "MOHD SUBHAN BIN GHARAT" },
                    { 157, "AHMAD KHUSHAIRIE BIN MOHD NASIR" },
                    { 158, "MASRINA AZMISAH BINTI AZMI " },
                    { 159, "LOW HAN BEN  " },
                    { 160, "CHOONG KIM LOON " },
                    { 161, "TONY TAY LIM HUAT" },
                    { 162, "WONG KEN FAH" },
                    { 163, "SOON WEE SENG" },
                    { 164, "KECK BOON BENG " },
                    { 165, "WONG PUI TIN " },
                    { 166, "WONG CHOI HOONG" },
                    { 167, "DINA TO XUEI EN" },
                    { 168, "LAM WAI HONG" },
                    { 169, "CHENG YAN PING" },
                    { 170, "BEE JOON NEE" },
                    { 171, "WONG KWOK BUN" },
                    { 172, "MUHAMMAD SYAHRUL NIZAM BIN SAARI" },
                    { 173, "AHMAD SYAHIR BIN NORDIN" },
                    { 174, "MOHAMAD NOORDIN BIN MAT ISA" },
                    { 175, "CHANG CHEK FEEI " },
                    { 176, "TENG WAI KIT" },
                    { 177, "LEE YOON YAW " },
                    { 178, "LIM PING CHEE" },
                    { 179, "YEN WOEI HWAN" },
                    { 180, "GOH GEOK MENG" },
                    { 181, "ABDUL RAZAK BIN IBRAHIM" },
                    { 182, "LEON BOON TEANG " },
                    { 183, "ONG CHEE BENG " },
                    { 184, "CHEAH CHEN SHEIN" },
                    { 185, "CHEAH WOON SHIN " },
                    { 186, "LEE WEI CHEW" },
                    { 187, "TAN SZE MIN" },
                    { 188, "CHAN WENG KIT" },
                    { 189, "NG BAN HWU " },
                    { 190, "TEOH CHIN POH" },
                    { 191, "TAN ZHI YANG" },
                    { 192, "LEE SIANG HI" },
                    { 193, "TAN KEAN AIK" },
                    { 194, "OOI HOON NI" },
                    { 195, "MUHAMMAD SAYUTHI BIN HUSSIN" },
                    { 196, "SELEHUDDIN BIN MAT ISA" },
                    { 197, "WONG YAT CHUEN" },
                    { 198, "PANG ENG CHEN" },
                    { 199, "NOOR EFENDI BIN NOORDIN" },
                    { 200, "NOR AZLAN BIN BAHARUL" },
                    { 201, "YONG SI KO " },
                    { 202, "LEONG CHEE MENG" },
                    { 203, "MOHD NAZMUN BIN MOHD NOOR" },
                    { 204, "NIK AZLY BIN NIK MAHMUD" },
                    { 205, "CHONG WEI KIAN" },
                    { 206, "EDDY SOFFIAN BIN MOHAMED" },
                    { 207, "GOH WEI KEONG " },
                    { 208, "MOHAMAD HASHRUL SHAHIRMAN BIN ABDUL HASHIM" },
                    { 209, "MD ROZAIMI SAZUAN BIN MOHD LAZIM" },
                    { 210, "AIMAN FAZRAN BIN MANSOR" },
                    { 211, "KAMARUL SAZAMIR BIN SAAD" },
                    { 212, "AZIZI BIN ISMAIL" },
                    { 213, "MUHAIMIM AZIZI BIN CHE MAHIUDDIN" },
                    { 214, "MOHD KHAIRUL IZHAM BIN JUSOH" },
                    { 215, "LEOH CHIA HOW" },
                    { 216, "HON BEE SIAH" },
                    { 217, "CHE MUHAMMAD HAFIZI BIN CHE YAAKUB" },
                    { 218, "MOHAMAD AZWAN BIN MOHD AZLI" },
                    { 219, "LEE WEI KEAT" },
                    { 220, "MOHD FAIRUZ BIN NOORDIN" },
                    { 221, "WAN NUR SYAZWANIE BINTI WAN MALZELAM" },
                    { 222, "NURLIYANA IZNI BINTI MOHD AL ADIB" },
                    { 223, "WONG LEE CHING" },
                    { 224, "TENGKU MOHD FAIZ BIN TENGKU HAMZAH" },
                    { 225, "KWOK YOONG HENG" },
                    { 226, "CHONG HONG TAT" },
                    { 227, "TEE BOON HONG " },
                    { 228, "KOU LEE SIAN " },
                    { 229, "CHEW SHYH PING " },
                    { 230, "IVAN SIM CHEE KOK" },
                    { 231, "TAN LU HUY" },
                    { 232, "LEE WAI KIT" },
                    { 233, "LIEW JIUN TYNG" },
                    { 234, "NUR AMIRA BINTI MOHD SENIN" },
                    { 235, "MOHD SHAH REZZA BIN SAHAK" },
                    { 236, "LEE CHENG LIAN" },
                    { 237, "NORITA BINTI ERELES" },
                    { 238, "TAN TIAN BOON" },
                    { 239, "ADELENE YAP SIEW WAI" },
                    { 240, "HAIRULIZAM BIN SAMAN" },
                    { 241, "TIONG CHOO SENG " },
                    { 242, "LO HANG SEM" },
                    { 243, "ARON KEE TECK JEN" },
                    { 244, "ANDY YEO JIA WEI" },
                    { 245, "VUN XIAO CHE" },
                    { 246, "VINCENT DRUCE" },
                    { 247, "KENNY TING SIE LUNG" },
                    { 248, "JOSEPH BERNARD DATO BALANJIU JR" },
                    { 249, "GRINGO HIEW SHING FOO" },
                    { 250, "QUEENY KONG" },
                    { 251, "CHOO JIUNN FUI" },
                    { 252, "SHELVY CARMEN WELFERD" },
                    { 253, "RANDALL RICKY SEDOMON" },
                    { 254, "ADI NASTASE BIN MOHAMAD JOEHAR" },
                    { 255, "ARSILLA KANAK @ MICHAEL" },
                    { 256, "MOHD ALFIE BIN AHMAD" },
                    { 257, "WONG VUN CHEH" },
                    { 258, "MUHAMMAD FAZLI BIN ZULKIFLI" },
                    { 259, "FARIS HAKIMI BIN ISMAIL" },
                    { 260, "NURUL SYAHIRA BINTI ASZAHAR" },
                    { 261, "MOHD AIZUDDIN BIN AHMAD" },
                    { 262, "RATHIKA A/P DANIEL " },
                    { 263, "INTAN LAILA SHAKIRA IDAYU BINTI ITAMRUZZAMAN" },
                    { 264, "JOESLINE CHEE JOE SING" },
                    { 265, "YIM CHIN SHIN" },
                    { 266, "ZULAIKHA BINTI ZAINAL ABIDIN" },
                    { 267, "ROBIATUL ADAWIAH BINTI RAMLAN" },
                    { 268, "DHIVYA GOWRI A/P PUSPANATHAN" },
                    { 269, "NUR SYAZANA BINTI MOHD ZAWAWI" },
                    { 270, "NUR DALILA BINTI RAMLI" },
                    { 271, "TEE MOY HWA" },
                    { 272, "LEE BEE KIM " },
                    { 273, "LIM SIN CHIN " },
                    { 274, "MUHAMMAD YUSRI VICKNESH" },
                    { 275, "LEONG KAH OI " },
                    { 276, "KONG LING YUN " },
                    { 277, "LEE HUI ZHI" },
                    { 278, "NOR NISA NAZURAH BINTI FIRDAUS" },
                    { 279, "SAMSIA BINTI ABDU RASAK" },
                    { 280, "NORFAZIRAH BINTI DULLAH" },
                    { 281, "HALIEDA BINTI AIMIE" },
                    { 282, "EDMUND LIM YIK CHIONG" },
                    { 283, "HOW SHYH JAE" },
                    { 284, "KEE BOON KHIT " },
                    { 285, "NG MUN KIM " },
                    { 286, "LEONG SU SHAN" },
                    { 287, "CHUAH LIM ZI XUAN" },
                    { 288, "NUUR DIYANA BINTI MOHD ARIFIN" },
                    { 289, "AHMAD HAZWAN BIN EMBONG" },
                    { 290, "WONG CHOOI WEI " },
                    { 291, "MOHD IZAN SYAZWAN BIN A.RAHIM" },
                    { 292, "MOHAMAD ADNAN BIN DAUD" },
                    { 293, "NORHIDAYAH BINTI BURHAN" },
                    { 294, "HO KOK ON" },
                    { 295, "NG KENG HOOI " },
                    { 296, "CHONG LI MIN" },
                    { 297, "MUHAMMAD HAKIM BIN SULAIMAN" }
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Employees");
        }
    }
}
